### ISSUE TITLE
[BUG] Cannot merge already merged cells after insert / duplicate a new row

### ISSUE THREAD

**Issue by Louis-Ni** [exceljs/exceljs#2317]
## 🐛 Bug Report

Lib version: ^4.3.0

## Steps To Reproduce

```javascript
 const startRow = 10
 let counter = 0
  item.forEach((item: any) => {
      worksheet.insertRow(prescrionStartAt+counter, [1, 2, 3, 4])
      worksheet.mergeCells(`A${startRow+counter}:D${startRow+counter}`)          
      counter++
  });
```
<img width="793" alt="image" src="https://github.com/exceljs/exceljs/assets/56672404/70d59e54-6fe0-4591-afba-2aa400ade87b">
the lines I added exceed line 12, it will cause an error, it's ok if I add 1 line below 10
but the **item**  is dynamic, I don't know how many lines should be added.

I had searched for a solution like:
[issues#1567](https://github.com/exceljs/exceljs/issues/1567#issuecomment-801428380)
but I can't find the property on the `sheet.model.merges`
## The expected behaviour:

it should be added for `n` new rows into the sheet, but it caused an error when my Excel temple has a merged line below line 10
Does anyone have ideas to fix this one?

**Comment by MGber** [comment]
I've addressed the bug topic in this comment: [link](https://github.com/exceljs/exceljs/issues/1567#issuecomment-1677355538).

**Comment by dinhhai96-vn** [comment]
The attributes assigned to cells in Excel are automatically assigned to that cell. You need to unmerge them first and then use the attributes you want. For example: A2-A4 is being merged, you want to add a line above, you need to unmerge and then add the line. Finally, find the location and merge it.

**Comment by imfurankase** [comment]
If you're facing issues with merged cells when inserting new rows using ExcelJS, here's a clear approach on how i handled this:

1. **Problem Recap**: ExcelJS may not automatically retain the merged state when inserting rows that involve merged cells, leading to conflicts and errors like "Cannot merge already merged cells."

2. **Solution Overview**: To handle this, we recommend(just in case):
   - **Unmerging Cells Temporarily**: Before inserting or duplicating rows, ensure all cells in the range are unmerged.
   - **Tracking Merged Cells**: Keep track of the original merged cell ranges.
   - **Re-merging Cells After Modifications**: After inserting or duplicating rows, use the tracked ranges to re-merge the cells.

3. **Utility Function Approach**: We created a utility function to check if cells in a range are already merged and merge them if needed. This function avoids merging cells that are already merged and handles merging cells dynamically.

### Example Code:

**Utility Function (`mergeCellsIfNeeded`)**:
```typescript
import ExcelJS from "exceljs";

/**
 * Merges cells in a given range if they are not already merged.
 *
 * @param worksheet - The ExcelJS worksheet object.
 * @param range - The cell range to merge, e.g., "A1:C3".
 */
export const mergeCellsIfNeeded = (
  worksheet: ExcelJS.Worksheet,
  range: string
) => {
  const [startCell, endCell] = range.split(":");
  const startRow = worksheet.getCell(startCell).row;
  const endRow = worksheet.getCell(endCell).row;
  const startCol = worksheet.getCell(startCell).col;
  const endCol = worksheet.getCell(endCell).col;

  let alreadyMerged = false;

  for (let row = startRow; row <= endRow; row++) {
    for (let col = startCol; col <= endCol; col++) {
      const cell = worksheet.getCell(row, col);
      if (cell.isMerged) {
        alreadyMerged = true;
        break;
      }
    }
    if (alreadyMerged) break;
  }

  if (!alreadyMerged) {
    worksheet.mergeCells(range);
  }
};
```

**Usage in Your Code**:
```typescript
import ExcelJS from "exceljs";
import { mergeCellsIfNeeded } from "src/utils/excelUtils";

export const modifyExcelSheet = async () => {
  const templateUrl = "/templates/example.xlsx"; // Your template path here

  try {
    // Load the template workbook
    const response = await fetch(templateUrl);
    const data = await response.arrayBuffer();
    const workbook = new ExcelJS.Workbook();
    await workbook.xlsx.load(data);

    const worksheet = workbook.getWorksheet(1);

    if (!worksheet) {
      console.error("Worksheet not found in the Excel file.");
      return;
    }

    // Merge cells if they are not already merged
    mergeCellsIfNeeded(worksheet, "A1:C1");
    worksheet.getCell("A1").value = "Merged Header";

    // Add new rows with merged cells
    const newRowNumber = worksheet.lastRow.number + 1;
    worksheet.insertRow(newRowNumber, ["Data1", "Data2", "Data3"]);
    mergeCellsIfNeeded(worksheet, `A${newRowNumber}:C${newRowNumber}`);
    worksheet.getCell(`A${newRowNumber}`).value = "Merged Row Data";

    // Save the modified workbook
    const buffer = await workbook.xlsx.writeBuffer();
    const blob = new Blob([buffer], {
      type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    });

    saveAs(blob, "ModifiedExample.xlsx");
  } catch (error) {
    console.error("Error modifying Excel file:", error);
  }
};
```

**Comment by IonelLupu** [comment]
I am still getting `Cannot merge already merged cells` even after using the `moveMergesModel` helper above. 😞  I even used [this approach](https://github.com/exceljs/exceljs/discussions/1967#discussioncomment-2172573) of unmerging the cells before merging them. Getting the same error. 

What can be done?
